version: '3'

services:
  catalog-service:
    image: siddhanthhn/catalog-service
    ports: 
     - "8000:80"
  redis:
    image: redis:alpine
  review-service:
    image: siddhanthhn/review-service
    ports:
    - "8050:90"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 20M
  order-service:
    image: siddhanthhn/order-service
    ports:
    - "8100:100"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 20M

